variables:
    IMAGE_NAME: wissamsaidi/ui-service
    IMAGE_TAG: v1
build_stage:
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script: 
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD 
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
